### ISSUE TITLE
What is the License for the Modules?

### ISSUE THREAD

**Issue by EVILEDLIBRE** [ikemen-engine/modules#1]
So, I know this might sound like nitpicking, but now that these game modes have been moved out of the engine itself and into their own repository; I think there really should be a License.txt file in here to indicate that they are indeed still covered under the MIT Expat License; like the engine itself is.

I'm assuming the intent is that they are still to be covered under the same license. But, technically, they're mods now and not part of the engine anymore like they used to be. So, I don't really know if having a line on the main engine page saying "The code is under the MIT Licence." really applies here anymore; technically speaking.

The License.txt file and the line one the main engine page "The code is under the MIT Licence." are specifically in reference to the game engine; not to anything else. These files are no longer part of the game engine. They are now stand alone mods that exist in their own stand alone repository that now don't have a license to them at all.

One might infer that the engine license should ripple through and cover these mods (considering much of the functionality of these mods was once part of the engine.) But, inferring something is not the same as actually having a license.

Mods are not the same as being part of the engine itself. I can't, for instance, just download a DOOM mod and assume it's under the same license as the DOOM engine that I am using.

Also, the ikemen-engine page https://github.com/ikemen-engine lists several repositories. Not all of which are MIT. The Ikemen_GO-Elecbyte-Screenpack for instance isn't even MIT compatible as it still contains elements from mugen that restrict commercial use. (I understand the reason for this co-existence; as we currently do not have a fully MIT compatible screen pack to replace this with.)

My point being, one should not simply assume that sense the ikemen-engine is MIT that all things listed on the ikemen-engine page are also automatically MIT. As we know that the Ikemen_GO-Elecbyte-Screenpack is not. So, that leaves the modules page that currently doesn't have a license listed as a sort of technical gray area.

**Comment by Flowrif** [comment]
sorry please close

**Comment by EVILEDLIBRE** [comment]
Issue has been resolved.

https://github.com/ikemen-engine/Ikemen-GO/issues/801
